[tox]
envlist = py{311}
allowlist_externals = rm
requires = tox-conda

[testenv]
deps=
    pip
    wheel
    setuptools
    numpy==2.2.4
    pytest
    pybind11
    Cython
    pytest-forked
    pytest-xdist
whitelist_externals = pytest
    /bin/rm
commands =
    pytest --forked -n 1 -v -x lcbuilder/tests/
allowlist_externals = rm

[gh]
python =
    3.11 = py311
allowlist_externals = rm
