[tox]
envlist = py{313}
allowlist_externals = rm
requires = tox-conda

[testenv]
deps=
    pip
    wheel
    setuptools
    numpy==2.2.4
    pytest
    pybind11
    Cython
    pytest-forked
whitelist_externals = pytest
    /bin/rm
commands =
    pytest --forked  -v -x lcbuilder/tests/
allowlist_externals = rm

[gh]
python =
    3.13 = py313
allowlist_externals = rm
